#!/usr/bin/env bash
#blablabla

i=1

while [ "$i" -le 10 ]
do
	case "$variable" in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
	esac
	i=$((i+1))
done
