#!/usr/bin/env bash
#blablabla 

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT

sudo bash -c "echo $ > /var/run/myscript.pid"

# Create PID file
echo $$ > /var/run/myscript.pid

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 1
done
