#!/usr/bin/env bash
# Script that creates a PID file and handles signals

sudo chmod o+w /var/run
PIDFILE="/var/run/myscript.pid"

# Create the PID file
echo $$ > "$PIDFILE"

# Handle signals
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PIDFILE"; exit 0' SIGQUIT
trap 'echo "I hate the kill command"; rm -f "$PIDFILE"; exit 0' SIGTERM

# Main loop
while true
do
    echo "To infinity and beyond"
    sleep 1
done
