#!/usr/bin/env bash
# File to write messages
# Target log file
LOG_FILE="/tmp/my_process"

# Main loop to write the "I am alive!" message
while true; do
    echo "I am alive! (PID: $$)" >> $LOG_FILE
    sleep 2
done
