#!/usr/bin/env bash
# File to write messages
OUTPUT_FILE="/tmp/my_process"

# Infinite loop writing "I am alive!" every 2 seconds
while true; do
    echo "I am alive!" >> "$OUTPUT_FILE"
    sleep 2
done
